apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafe-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cafe-app
  template:
    metadata:
      labels:
        app: cafe-app
    spec:
      containers:
      - name: php-app1
        image: php:8.0-apache
        ports:
        - containerPort: 80
